[package]
name = "nostr-q"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
nostr.workspace = true
tracing.workspace = true
nostr-q-core.workspace = true
nostr-q-store.workspace = true
nostr-q-relay.workspace = true

[dev-dependencies]
tempfile.workspace = true
