[package]
name = "nostr-q-relay"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
tokio-util.workspace = true
serde.workspace = true
serde_json.workspace = true
nostr.workspace = true
nostr-sdk.workspace = true
nostr-q-core.workspace = true
tracing.workspace = true
futures.workspace = true
tokio-tungstenite.workspace = true
